# Imports

In [ ]:
import cv2 
import numpy as np

# Qestion 1: DILATION 

## part 1

### Step 1: Read the input binary image

In [ ]:
# The image is read in grayscale mode.
image_1 = cv2.imread(r"imgs\circle-square.png", cv2.IMREAD_GRAYSCALE)

# Check if the image was loaded successfully
if image_1 is None:
    raise IOError(r"Error: Could not read the image 'imgs\circle-square.png'.")

In [24]:
image_1

array([[254, 152, 163, ..., 163, 160, 218],
       [252,   0,   0, ...,   0,   0, 171],
       [252,   0,   0, ...,   0,   0, 171],
       ...,
       [252,   0,   0, ...,   0,   0, 171],
       [252,   0,   0, ...,   0,   0, 171],
       [252,   0,   0, ...,   0,   0, 171]], dtype=uint8)

In [25]:
image_1.shape 

(195, 258)

In [26]:
type(image_1)

numpy.ndarray

### Step 2: Ensure the image is binary


In [27]:
# Morphological dilation assumes a binary image where:
# - Foreground pixels are white (255)
# - Background pixels are black (0)
# We apply a threshold to guarantee a clean binary image.
_, binary_image_1 = cv2.threshold(image_1, 127, 255, cv2.THRESH_BINARY)

In [28]:
binary_image_1

array([[255, 255, 255, ..., 255, 255, 255],
       [255,   0,   0, ...,   0,   0, 255],
       [255,   0,   0, ...,   0,   0, 255],
       ...,
       [255,   0,   0, ...,   0,   0, 255],
       [255,   0,   0, ...,   0,   0, 255],
       [255,   0,   0, ...,   0,   0, 255]], dtype=uint8)

### Step 3: Define kernel sizes for comparison

In [29]:
# Different kernel sizes allow us to observe how the amount of dilation increases with the scale of the structuring element.
kernel_sizes = [4, 7, 10, 15, 20]

### Step 4,5: Apply morphological dilation for each kernel size and save the result


In [30]:
# Morphological Dilation:
# - Expands the white (foreground) regions in a binary image
# - Adds pixels to object boundaries
# The shape of the structuring element affects *how* objects grow,
# while the size affects *how much* they grow.
for size in kernel_sizes:
    kernel_dim = (size, size)

    # Square structuring element
    square_kernel = cv2.getStructuringElement(
        cv2.MORPH_RECT,
        kernel_dim
    )

    # Circular (disk-shaped) structuring element
    circular_kernel = cv2.getStructuringElement(
        cv2.MORPH_ELLIPSE,
        kernel_dim
    )

    # Apply dilation
    dilated_square = cv2.dilate(binary_image_1, square_kernel, iterations=1)
    dilated_circular = cv2.dilate(binary_image_1, circular_kernel, iterations=1)

    
    # Step 5: Save the results
    
    cv2.imwrite(f"square-circle-square-{size}.png", dilated_square)
    cv2.imwrite(f"square-circle-circle-{size}.png", dilated_circular)

In [31]:
# an example of Square structuring element
square_kernel = cv2.getStructuringElement(cv2.MORPH_RECT,(5,5))
square_kernel

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=uint8)

In [32]:
# an example of ciecle structuring element
circular_kernel = cv2.getStructuringElement(cv2.MORPH_ELLIPSE,(5,5))
circular_kernel

array([[0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0]], dtype=uint8)

## Part 2: Pepper noise removal

### Step 1: Read the input grayscale image


In [33]:
# The image is read in grayscale mode . pepper noise typically appears as dark pixels in intensity images.
image_2 = cv2.imread(r"imgs\Cameraman.png", cv2.IMREAD_GRAYSCALE)

# Check if the image was loaded successfully
if image_2 is None:
    raise IOError("Error: Could not read the image 'cameraman.png'.")

In [34]:
image_2

array([[199, 199, 200, ..., 190, 190, 190],
       [199, 199, 200, ..., 190, 190, 190],
       [200, 200, 199, ..., 191, 191, 191],
       ...,
       [ 25,  25,  24, ..., 136, 143, 118],
       [ 26,  25,  26, ..., 147, 154, 144],
       [ 25,  25,  25, ..., 146, 146, 151]], dtype=uint8)

### Step 2: Define multiple kernel sizes

In [35]:
kernel_sizes = [3, 5, 7, 9, 11]

### Step 3,4 : Apply dilation using different kernels and save the results

In [ ]:
for size in kernel_sizes:
    kernel_dim = (size, size)

    # Circular (disk-shaped) structuring element
    #
    # Rationale:
    # - Circular kernels expand pixels uniformly in all directions
    # - They avoid directional artifacts that square kernels may introduce
    structuring_element = cv2.getStructuringElement(
        cv2.MORPH_ELLIPSE,
        kernel_dim
    )

    # Apply morphological dilation
    denoised_image = cv2.dilate(
        image_2,
        structuring_element,
        iterations=1
    )

   
    # Step 4 : Save the result for this kernel size
    
    cv2.imwrite(f"cameraman-denoised-{size}.png", denoised_image)

## Part 3: Edge detection

### Step 1: Read the input grayscale image


In [37]:
image_3 = cv2.imread(r"imgs\Lady.png", cv2.IMREAD_GRAYSCALE)

if image_3 is None:
    raise IOError("Error: Could not read the image 'lady.png'.")

In [44]:
image_3

array([[159, 159, 157, ..., 167, 151, 118],
       [159, 159, 157, ..., 167, 151, 118],
       [159, 159, 157, ..., 167, 151, 118],
       ...,
       [ 20,  28,  24, ...,  90,  86,  84],
       [ 22,  34,  30, ...,  90,  92,  96],
       [ 22,  34,  30, ...,  90,  92,  96]], dtype=uint8)

### Step 2: Define multiple kernel sizes


In [38]:
# Using multiple kernel sizes allows us to observe:
# - Small kernels  -> thin, fine edges
# - Large kernels  -> thicker, more prominent edges
kernel_sizes = [3, 5, 7, 9, 11]

### Step 3,4: Apply dilation and edge extraction for each kernel and save


In [45]:
for size in kernel_sizes:
    kernel_dim = (size, size)

    
    # 1. Square structuring element (RECT)
   
    square_kernel = cv2.getStructuringElement(
        cv2.MORPH_RECT,
        kernel_dim
    )

    # Apply dilation with square kernel
    dilated_square = cv2.dilate(
        image_3,
        square_kernel,
        iterations=1
    )

    # Edge detection using morphological gradient idea
    edge_square = cv2.subtract(dilated_square, image_3)

    # Save result
    cv2.imwrite(f"lady-edge-square-{size}.png", edge_square)

    
    # 2. Circular structuring element (ELLIPSE)
    
    circular_kernel = cv2.getStructuringElement(
        cv2.MORPH_ELLIPSE,
        kernel_dim
    )

    # Apply dilation with circular kernel
    dilated_circular = cv2.dilate(
        image_3,
        circular_kernel,
        iterations=1
    )

    # Edge detection using morphological gradient idea
    edge_circular = cv2.subtract(dilated_circular, image_3)

    # Save result
    cv2.imwrite(f"lady-edge-circular-{size}.png", edge_circular)


# Question 2 : EROSION

## Part 1

### Step 1: Define multiple kernel sizes

In [40]:
# Larger kernels result in stronger erosion effects.
kernel_sizes = [4, 7, 10, 15, 20]

### Step 2,3: Apply erosion using different kernels and saving


In [46]:
for size in kernel_sizes:
    kernel_dim = (size, size)

    # Square structuring element
    square_kernel = cv2.getStructuringElement(
        cv2.MORPH_RECT,
        kernel_dim
    )

    # Circular (disk-shaped) structuring element
    circular_kernel = cv2.getStructuringElement(
        cv2.MORPH_ELLIPSE,
        kernel_dim
    )

    # Apply erosion
    eroded_square = cv2.erode(binary_image_1, square_kernel, iterations=1)
    eroded_circular = cv2.erode(binary_image_1, circular_kernel, iterations=1)

    # Step 3: Save results separately
    cv2.imwrite(
        f"circle-square-erode-square-{size}.png",
        eroded_square
    )

    cv2.imwrite(
        f"circle-square-erode-circle-{size}.png",
        eroded_circular
    )

## Part2: Salt and pepper noise removal

### Step 1: Define multiple kernel sizes


In [ ]:
kernel_sizes = [3, 5, 7, 9, 11]

### Step 2, 3: Apply erosion using different kernels and save the results


In [ ]:
for size in kernel_sizes:
    kernel_dim = (size, size)

    # Structuring element choice:
    # - Circular kernel avoids directional artifacts
    # - Small-to-medium sizes limit detail loss
    structuring_element = cv2.getStructuringElement(
        cv2.MORPH_ELLIPSE,
        kernel_dim
    )

    # Apply morphological erosion
    eroded_image = cv2.erode(
        image_2,
        structuring_element,
        iterations=1
    )

    
    # Step 3: Save the result for this kernel size
   
    cv2.imwrite(f"cameraman-erode-{size}.png", eroded_image)